{
    "error": 4,
    "mensaje_error": "Ya existe un usuario con estas credenciales"
}